import '../globals.css';
import {AuthProvider} from "@/context/AuthContext";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
    return (
        // <AuthProvider>
            <section>
                {children}
            </section>
        // </AuthProvider>
    );
}