import { Toaster } from "sonner"
import { Geist, Geist_Mono, Urbanist } from "next/font/google";
import "./globals.css";

import {AuthProvider} from "@/context/AuthContext";
import AOS from "aos";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import AOSInit from "@/components/AOSInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const urbanist = Urbanist({
    variable: "--font-urbanist",
    subsets: ["latin"],
    weight: "400"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${urbanist.variable} ${geistSans.variable} ${geistMono.variable} antialiased font-main bg-[#FAFAFA]`}
            >
                <AuthProvider>
                    <AOSInit />
                    {/* <Navbar /> */}
                        {children}
                    {/* <Footer /> */}
                </AuthProvider>
            </body>
        </html>
    );
}
