import { Urbanist } from "next/font/google";
import './globals.css';
import {AuthProvider} from "@/context/AuthContext";
import {TokenRefreshAlertDialog} from "@/components/TokenRefreshAlertDialog";
import {Toaster} from "sonner";

const urbanist = Urbanist({
    variable: "--font-urbanist",
    subsets: ["latin"],
    weight: "400"
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${urbanist.variable} antialiased font-main bg-[#FAFAFA]`}>
            <AuthProvider>
                <Toaster
                    richColors
                    toastOptions={{
                        style: {
                            pointerEvents: 'auto',
                            width: 'fit-content'
                        }
                    }}
                />
                <TokenRefreshAlertDialog />
                {children}
            </AuthProvider>
        </body>
        </html>
    );
}

