import { Urbanist } from "next/font/google";
import './globals.css';
import {AuthProvider} from "@/context/AuthContext";

const urbanist = Urbanist({
    variable: "--font-urbanist",
    subsets: ["latin"],
    weight: "400"
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${urbanist.variable} antialiased font-main bg-[#FAFAFA]`}>
            <AuthProvider>
                {children}
            </AuthProvider>
        </body>
        </html>
    );
}

