import { Toaster } from "sonner"
import { Urbanist } from "next/font/google";

import '../globals.css';
import {AppSidebar} from "@/components/app-sidebar";
import {SidebarInset, SidebarProvider} from "@/components/ui/sidebar";
import {SiteHeader} from "@/components/site-header";


const urbanist = Urbanist({
    variable: "--font-urbanist",
    subsets: ["latin"],
    weight: "400"
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdministratorLayout({ children }) {
    return (
        <SidebarProvider
            style={
                {
                    "--sidebar-width": "calc(var(--spacing) * 72)",
                    "--header-height": "calc(var(--spacing) * 12)"
                }
            }>
            <AppSidebar variant="inset" />
            <SidebarInset>
                <SiteHeader />
                <Toaster richColors
                         toastOptions={{
                             style: {
                                 pointerEvents: 'auto',
                                 width: 'fit-content'
                             }
                         }}
                />
                {/*<div className="flex flex-1 flex-col">*/}
                {/*  <div className="@container/main flex flex-1 flex-col gap-2">*/}
                <div className="md:p-6">
                    {children}
                </div>
                {/*  </div>*/}
                {/*</div>*/}
            </SidebarInset>
        </SidebarProvider>
    );
}
